// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities.Accounts;

public partial class AccountEntity
{
    public int AccountId { get; set; }

    public Guid? AccountGlobalUniqueId { get; set; }

    public string AccountNumber { get; set; }

    public string ModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public string LegalName { get; set; }

    /// <summary>
    /// Gets or sets the Akuiteo routing code. NVARCHAR(255) is provisional pending the definitive Akuiteo contract.
    /// </summary>
    public string AccountRoutingCode { get; set; }

    /// <summary>
    /// Gets or sets the Akuiteo routing label. NVARCHAR(255) is provisional pending the definitive Akuiteo contract.
    /// </summary>
    public string AccountRoutingLabel { get; set; }

    /// <summary>
    /// Gets or sets the Akuiteo legal-form label. NVARCHAR(255) is provisional pending the definitive Akuiteo contract.
    /// </summary>
    public string AccountLegalFormLabel { get; set; }

    /// <summary>
    /// Gets or sets the Akuiteo electronic address identifier. NVARCHAR(255) is provisional pending the definitive
    /// Akuiteo contract.
    /// </summary>
    public string AccountElectronicAddressId { get; set; }

    public virtual ICollection<RoleEntity> RoleEntity { get; set; } = new List<RoleEntity>();
}
