// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities.Accounts;

public partial class AccountEntity
{
    public int AccountId { get; set; }

    public Guid? AccountGlobalUniqueId { get; set; }

    public string AccountNumber { get; set; }

    public string ModifiedBy { get; set; }

    public string CreatedBy { get; set; }

    public string LegalName { get; set; }

    public virtual ICollection<RoleEntity> RoleEntity { get; set; } = new List<RoleEntity>();
}