// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pulse.Registry.Domain.Entities.Contacts;
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities.Accounts;

public partial class RoleEntity
{
    public int AccountId { get; set; }

    public int ContactId { get; set; }

    public int? RoleDuplicatesCounter { get; set; }

    public Guid? AccountGlobalUniqueId { get; set; }

    public Guid? ContactGlobalUniqueId { get; set; }

    public string AccountNumber { get; set; }

    public string ContactEmail { get; set; }

    public bool? ContactFlagPortailFactures { get; set; }

    public bool? ContactFlagMainContact { get; set; }

    public virtual AccountEntity Account { get; set; }

    public virtual ContactEntity Contact { get; set; }
}