<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Provider\**" />
    <EmbeddedResource Remove="Provider\**" />
    <None Remove="Provider\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.1" />
    <PackageReference Include="EFCore.BulkExtensions" Version="8.0.4" />
    <PackageReference Include="Kpmg.ExceptionMiddleware" Version="1.73.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
	  <PackageReference Include="Polly" Version="8.4.2" />
	  <PackageReference Include="Pulse.Back.Events" Version="1.73.158" />
	  <PackageReference Include="System.Runtime.Caching" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContactRegistry.Domain\ContactRegistry.Domain.csproj" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ContactRegistry.Application\ContactRegistry.Application.csproj" />
	</ItemGroup>


</Project>
