//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registry.AzureFuctions {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class local : global::System.Configuration.ApplicationSettingsBase {
        
        private static local defaultInstance = ((local)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new local())));
        
        public static local Default {
            get {
                return defaultInstance;
            }
        }
    }
}
