// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Application.Models.Accounts;
using Application.Models.Contacts;
using Domain.Entities;
using Domain.Entities.Accounts;
using Domain.Entities.Audits;
using Domain.Entities.Contacts;
using Microsoft.EntityFrameworkCore;
using Pulse.Registry.Domain.Entities;

namespace Pulse.Registry.Domain.Context;

public partial class RefContext : DbContext
{
    public RefContext(DbContextOptions<RefContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RefAccountEntity> RefAccountEntity { get; set; }

    public virtual DbSet<RefContactEntity> RefContactEntity { get; set; }

    public virtual DbSet<RefRoleEntity> RefRoleEntity { get; set; }

    public virtual DbSet<RefAccountEntity> RefAccount { get; set; }

    public virtual DbSet<RefContactEntity> RefContact { get; set; }

    public virtual DbSet<RefRoleEntity> RefRole { get; set; }

    public virtual DbSet<RegOperationEntity> RegOperationEntity { get; set; }

    public virtual DbSet<RegOperationEntity> Operation { get; set; }

    public virtual DbSet<AccountEntity> AccountEntities { get; set; }

    public virtual DbSet<ContactEntity> ContactEntities { get; set; }

    public virtual DbSet<RoleEntity> RoleEntities { get; set; }

    public virtual DbSet<DeepValidationEntity> DeepValidationEntities { get; set; }

    public virtual DbSet<RefOfferEntity> OfferEntities { get; set; }

    public virtual DbSet<PendingOperationEntity> PendingOperations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RefOfferEntity>(entity =>
        {
            // Table & PK
            entity.ToTable("Offer", "ref");
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            // Columns
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.ClientEmail)
                .HasMaxLength(255);

            entity.Property(e => e.CollaboratorEmail)
                .HasMaxLength(255);

            entity.Property(e => e.MissionLeaderEmail)
                .HasMaxLength(255);

            entity.Property(e => e.AccountingExpertEmail)
                .HasMaxLength(255);

            entity.Property(e => e.Offer)
                .IsRequired()
                .HasColumnName("Offer")
                .HasMaxLength(255);

            entity.Property(e => e.MigrationStatus)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.BatchId)
                .IsRequired()
                .HasColumnType("uniqueidentifier");
        });


        modelBuilder.Entity<RefAccountEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Account", "ref");

            entity.Property(e => e.AccountBillingEmail).HasMaxLength(255);
            entity.Property(e => e.AccountBillingFax).HasMaxLength(50);
            entity.Property(e => e.AccountBillingPhone).HasMaxLength(50);
            entity.Property(e => e.AccountCodeFormeJuridique).HasMaxLength(50);
            entity.Property(e => e.AccountCommercialName).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryEmail).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryFax).HasMaxLength(50);
            entity.Property(e => e.AccountDeliveryPhone).HasMaxLength(50);
            entity.Property(e => e.AccountEmail).HasMaxLength(100);
            entity.Property(e => e.AccountEscCategory).HasMaxLength(50);
            entity.Property(e => e.AccountFormeJuridique).HasMaxLength(255);
            entity.Property(e => e.AccountIsin)
                .HasMaxLength(100)
                .HasColumnName("AccountISIN");
            entity.Property(e => e.AccountNafIdentifier).HasMaxLength(50);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountRegimeFiscal).HasMaxLength(50);
            entity.Property(e => e.AccountRegisterIdentification1).HasMaxLength(50);
            entity.Property(e => e.AccountSectorCode).HasMaxLength(50);
            entity.Property(e => e.AccountSourceName).HasMaxLength(100);
            entity.Property(e => e.AccountStaffSize).HasMaxLength(50);
            entity.Property(e => e.AccountStaffSizeSlice).HasMaxLength(50);
            entity.Property(e => e.AccountTaxationSystem).HasMaxLength(100);
            entity.Property(e => e.AccountTaxeValeurAjoutee).HasMaxLength(50);
            entity.Property(e => e.AccountTurnover).HasMaxLength(50);
            entity.Property(e => e.AccountType).HasMaxLength(50);
            entity.Property(e => e.AccountTypeTenueComptable).HasMaxLength(50);
            entity.Property(e => e.BillingAddressLine1).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine2).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine3).HasMaxLength(255);
            entity.Property(e => e.BillingCity).HasMaxLength(50);
            entity.Property(e => e.BillingCountry).HasMaxLength(50);
            entity.Property(e => e.BillingState).HasMaxLength(50);
            entity.Property(e => e.BillingZipCode).HasMaxLength(20);
            entity.Property(e => e.DeliveryAddressLine1).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine3).HasMaxLength(255);
            entity.Property(e => e.DeliveryCity).HasMaxLength(50);
            entity.Property(e => e.DeliveryCountry).HasMaxLength(50);
            entity.Property(e => e.DeliveryState).HasMaxLength(50);
            entity.Property(e => e.DeliveryZipCode).HasMaxLength(20);
            entity.Property(e => e.LegalName).HasMaxLength(255);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<RefRoleEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Role", "ref");

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RoleSource)
            .HasDefaultValue(null);
        });

        modelBuilder.Entity<RefContactEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Contact", "ref");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.JobDescription).HasMaxLength(255);
            entity.Property(e => e.LandPhone).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.MobilePhone).HasMaxLength(255);
            entity.Property(e => e.OfficeCode).HasMaxLength(50);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ContactSource)
            .HasDefaultValue(null);
            entity.Property(e => e.AccountNumber)
            .IsRequired(false)
            .HasDefaultValue(null)
            .HasMaxLength(100);
        });

        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.ToTable("Accounts", "Account");

            entity.HasKey(e => e.AccountId)
                  .HasName("C_Account_PK");

            entity.Property(e => e.AccountId)
                  .IsRequired();

            entity.Property(e => e.AccountNumber)
                  .IsRequired()
                  .HasMaxLength(100)
                  .HasColumnType("VARCHAR");
        });

        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.ToTable("Roles", "Account");

            entity.HasKey(e => new { e.ContactId, e.AccountId })
                  .HasName("C_Role_PK");

            entity.HasIndex(e => new { e.AccountId, e.ContactId })
                  .IsUnique()
                  .HasName("C_Role_AccountId_ContactId");

            entity.Property(e => e.RoleDuplicatesCounter)
                  .HasColumnType("INT");

            entity.Property(e => e.AccountGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.ContactGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.AccountNumber)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.ContactEmail)
                  .HasMaxLength(255)
                  .HasColumnType("NVARCHAR");

            entity.HasOne<AccountEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.AccountId)
                  .HasConstraintName("C_Account_Role_FK");

            entity.HasOne<ContactEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.ContactId)
                  .HasConstraintName("C_Account_Contact_FK");
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.ToTable("Contacts", "Contact");

            entity.HasKey(e => e.ContactId)
                  .HasName("C_Contact_PK");

            entity.Property(e => e.ContactId)
                  .IsRequired();

            entity.Property(e => e.ContactGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(250)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.Type)
                  .IsRequired()
                  .HasMaxLength(20)
                  .HasColumnType("VARCHAR");
        });

        modelBuilder.Entity<DeepValidationEntity>(entity =>
        {
            entity.ToTable("DeepValidations", "Audit");

            entity.HasKey(e => e.Id);

            entity.Property(p => p.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<RegOperationEntity>(entity =>
        {
            entity.ToTable("Operations", "reg");

            entity.Property(e => e.LastStatusApprovalBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Operation)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ApprovalStatus).HasMaxLength(20);
            entity.Property(e => e.Type)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBySystem).HasDefaultValue(false);
        });

        modelBuilder.Entity<PendingOperationEntity>(entity =>
        {
            entity.HasKey(o => o.Id);
            entity.ToView("PendingOperations", "reg");
        });


        #region archive
        modelBuilder.Entity<ArchivedRefAccount>(entity =>
        {
            entity.ToTable("RefAccount", "Archive");
        });

        modelBuilder.Entity<ArchivedRefContact>(entity =>
        {
            entity.ToTable("RefContact", "Archive");
        });

        modelBuilder.Entity<ArchivedRefRole>(entity =>
        {
            entity.ToTable("RefRole", "Archive");
        });

        modelBuilder.Entity<ArchivedDeepValidation>(entity =>
        {
            entity.ToTable("DeepValidations", "Archive");
        });

        modelBuilder.Entity<ArchivedRegOperation>(entity =>
        {
            entity.ToTable("Operation", "Archive");
        });
        #endregion
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}