// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Application.Models.Accounts;
using Application.Models.Contacts;
using Domain.Entities.Accounts;
using Domain.Entities.Audits;
using Domain.Entities.Contacts;
using Microsoft.EntityFrameworkCore;
using Pulse.ContactRegistry.Domain.Entities;

namespace Pulse.ContactRegistry.Domain.Context;

public partial class RefContext : DbContext
{
    public RefContext(DbContextOptions<RefContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RefAccountEntity> RefAccountEntity { get; set; }

    public virtual DbSet<RefContactEntity> RefContactEntity { get; set; }

    public virtual DbSet<RefRoleEntity> RefRoleEntity { get; set; }

    public virtual DbSet<RegAccountEntity> RegAccountEntity { get; set; }

    public virtual DbSet<RegContactEntity> RegContactEntity { get; set; }

    public virtual DbSet<RegOperationEntity> RegOperationEntity { get; set; }

    public virtual DbSet<RegRoleEntity> RegRoleEntity { get; set; }

    public virtual DbSet<AccountEntity> AccountEntities { get; set; }

    public virtual DbSet<ContactEntity> ContactEntities { get; set; }

    public virtual DbSet<RoleEntity> RoleEntities { get; set; }

    public virtual DbSet<DeepValidationEntity> DeepValidationEntities { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId);
        });

        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.HasKey(e => new { e.ContactEmail, e.AccountNumber });
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId);
        });

        modelBuilder.Entity<RefAccountEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Account", "ref");

            entity.Property(e => e.AccountBillingEmail).HasMaxLength(255);
            entity.Property(e => e.AccountBillingFax).HasMaxLength(50);
            entity.Property(e => e.AccountBillingPhone).HasMaxLength(50);
            entity.Property(e => e.AccountCodeFormeJuridique).HasMaxLength(50);
            entity.Property(e => e.AccountCommercialName).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryEmail).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryFax).HasMaxLength(50);
            entity.Property(e => e.AccountDeliveryPhone).HasMaxLength(50);
            entity.Property(e => e.AccountEmail).HasMaxLength(100);
            entity.Property(e => e.AccountEscCategory).HasMaxLength(50);
            entity.Property(e => e.AccountFormeJuridique).HasMaxLength(255);
            entity.Property(e => e.AccountIsin)
                .HasMaxLength(100)
                .HasColumnName("AccountISIN");
            entity.Property(e => e.AccountNafIdentifier).HasMaxLength(50);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountRegimeFiscal).HasMaxLength(50);
            entity.Property(e => e.AccountRegisterIdentification1).HasMaxLength(50);
            entity.Property(e => e.AccountSectorCode).HasMaxLength(50);
            entity.Property(e => e.AccountSourceName).HasMaxLength(100);
            entity.Property(e => e.AccountStaffSize).HasMaxLength(50);
            entity.Property(e => e.AccountStaffSizeSlice).HasMaxLength(50);
            entity.Property(e => e.AccountTaxationSystem).HasMaxLength(100);
            entity.Property(e => e.AccountTaxeValeurAjoutee).HasMaxLength(50);
            entity.Property(e => e.AccountTurnover).HasMaxLength(50);
            entity.Property(e => e.AccountType).HasMaxLength(50);
            entity.Property(e => e.AccountTypeTenueComptable).HasMaxLength(50);
            entity.Property(e => e.BillingAddressLine1).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine2).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine3).HasMaxLength(255);
            entity.Property(e => e.BillingCity).HasMaxLength(50);
            entity.Property(e => e.BillingCountry).HasMaxLength(50);
            entity.Property(e => e.BillingState).HasMaxLength(50);
            entity.Property(e => e.BillingZipCode).HasMaxLength(20);
            entity.Property(e => e.DeliveryAddressLine1).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine3).HasMaxLength(255);
            entity.Property(e => e.DeliveryCity).HasMaxLength(50);
            entity.Property(e => e.DeliveryCountry).HasMaxLength(50);
            entity.Property(e => e.DeliveryState).HasMaxLength(50);
            entity.Property(e => e.DeliveryZipCode).HasMaxLength(20);
            entity.Property(e => e.LegalName).HasMaxLength(255);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });


        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.ToTable("Roles", "Account");

            entity.HasKey(e => new { e.ContactId, e.AccountId })
                  .HasName("C_Role_PK");

            entity.HasIndex(e => new { e.AccountId, e.ContactId })
                  .IsUnique()
                  .HasName("C_Role_AccountId_ContactId");

            entity.Property(e => e.IsFavorite)
                  .HasColumnType("BIT");

            entity.Property(e => e.IsSignatory)
                  .HasColumnType("BIT");

            entity.Property(e => e.IsDelegation)
                  .HasColumnType("BIT");

            entity.Property(e => e.RoleDuplicatesCounter)
                  .HasColumnType("INT");

            entity.Property(e => e.AccountGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.ContactGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.DelegatorContactId)
                  .IsRequired()
                  .HasColumnType("INT");

            entity.Property(e => e.AccountNumber)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.ContactEmail)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.HasOne<AccountEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.AccountId)
                  .HasConstraintName("C_Account_Role_FK");

            entity.HasOne<ContactEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.ContactId)
                  .HasConstraintName("C_Account_Contact_FK");
        });

        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.ToTable("Accounts", "Account");

            entity.HasKey(e => e.AccountId)
                  .HasName("C_Account_PK");

            entity.Property(e => e.AccountId)
                  .IsRequired();

            entity.Property(e => e.AccountNumber)
                  .IsRequired()
                  .HasMaxLength(100)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.LegalName)
                  .IsRequired()
                  .HasMaxLength(255)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.IsActive)
                  .IsRequired()
                  .HasColumnType("BIT");

            entity.Property(e => e.Siret)
                  .HasMaxLength(150)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.CreationDate)
                  .IsRequired()
                  .HasColumnType("DATETIME2(7)");

            entity.Property(e => e.UpdatedDate)
                  .HasColumnType("DATETIME2(7)");

            entity.Property(e => e.Status)
                  .IsRequired()
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");
        });


        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.ToTable("Roles", "Account");

            entity.HasKey(e => new { e.ContactId, e.AccountId })
                  .HasName("C_Role_PK");

            entity.HasIndex(e => new { e.AccountId, e.ContactId })
                  .IsUnique()
                  .HasName("C_Role_AccountId_ContactId");

            entity.Property(e => e.IsFavorite)
                  .HasColumnType("BIT");

            entity.Property(e => e.IsSignatory)
                  .HasColumnType("BIT");

            entity.Property(e => e.IsDelegation)
                  .HasColumnType("BIT");

            entity.Property(e => e.RoleDuplicatesCounter)
                  .HasColumnType("INT");

            entity.Property(e => e.AccountGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.ContactGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.DelegatorContactId)
                  .HasColumnType("INT");

            entity.Property(e => e.AccountNumber)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.ContactEmail)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.HasOne<AccountEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.AccountId)
                  .HasConstraintName("C_Account_Role_FK");

            entity.HasOne<ContactEntity>()
                  .WithMany()
                  .HasForeignKey(e => e.ContactId)
                  .HasConstraintName("C_Account_Contact_FK");
        });

        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.ToTable("Accounts", "Account");

            entity.HasKey(e => e.AccountId)
                  .HasName("C_Account_PK");

            entity.Property(e => e.AccountId)
                  .IsRequired();

            entity.Property(e => e.AccountNumber)
                  .IsRequired()
                  .HasMaxLength(100)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.LegalName)
                  .IsRequired()
                  .HasMaxLength(255)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.IsActive)
                  .IsRequired()
                  .HasColumnType("BIT");

            entity.Property(e => e.Siret)
                  .HasMaxLength(150)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.CreationDate)
                  .IsRequired()
                  .HasColumnType("DATETIME2(7)");

            entity.Property(e => e.UpdatedDate)
                  .HasColumnType("DATETIME2(7)");

            entity.Property(e => e.Status)
                  .IsRequired()
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.ToTable("Contacts", "Contact");

            entity.HasKey(e => e.ContactId)
                  .HasName("C_Contact_PK");

            entity.Property(e => e.ContactId)
                  .IsRequired();

            entity.Property(e => e.ContactGlobalUniqueId)
                  .HasColumnType("UNIQUEIDENTIFIER");

            entity.Property(e => e.FirstName)
                  .IsRequired()
                  .HasMaxLength(250)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.LastName)
                  .IsRequired()
                  .HasMaxLength(250)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.Email)
                  .IsRequired()
                  .HasMaxLength(250)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.Type)
                  .IsRequired()
                  .HasMaxLength(20)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.Status)
                  .HasMaxLength(20)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.PersonaName)
                  .IsRequired()
                  .HasMaxLength(50)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.Office)
                  .HasMaxLength(250)
                  .HasColumnType("VARCHAR");

            entity.Property(e => e.CreationDate)
                  .IsRequired()
                  .HasColumnType("DATETIME2")
                  .HasDefaultValueSql("GETDATE()");

            entity.Property(e => e.LastUpdateDate)
                  .HasColumnType("DATETIME2");

            entity.Property(e => e.IsActive)
                  .IsRequired()
                  .HasColumnType("BIT")
                  .HasDefaultValue(true);

            entity.Property(e => e.LandPhone)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.MobilePhone)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");

            entity.Property(e => e.Source)
                  .HasMaxLength(50)
                  .HasColumnType("NVARCHAR");
        });

        modelBuilder.Entity<RefContactEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Contact", "ref");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.JobDescription).HasMaxLength(255);
            entity.Property(e => e.LandPhone).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.MobilePhone).HasMaxLength(255);
            entity.Property(e => e.OfficeCode).HasMaxLength(50);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });


        modelBuilder.Entity<RefRoleEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Role", "ref");

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<RegAccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountNumber);

            entity.ToTable("Account", "reg");

            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.AccountBillingEmail).HasMaxLength(255);
            entity.Property(e => e.AccountBillingFax).HasMaxLength(50);
            entity.Property(e => e.AccountCodeFormeJuridique).HasMaxLength(50);
            entity.Property(e => e.AccountCommercialName).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryEmail).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryFax).HasMaxLength(50);
            entity.Property(e => e.AccountEmail).HasMaxLength(100);
            entity.Property(e => e.AccountEscCategory).HasMaxLength(50);
            entity.Property(e => e.AccountFlagEscactif).HasColumnName("AccountFlagESCActif");
            entity.Property(e => e.AccountFormeJuridique).HasMaxLength(255);
            entity.Property(e => e.AccountIsin)
                .HasMaxLength(100)
                .HasColumnName("AccountISIN");
            entity.Property(e => e.AccountNafIdentifier).HasMaxLength(50);
            entity.Property(e => e.AccountRegimeFiscal).HasMaxLength(50);
            entity.Property(e => e.AccountRegisterIdentification1).HasMaxLength(50);
            entity.Property(e => e.AccountSectorCode).HasMaxLength(50);
            entity.Property(e => e.AccountSourceName).HasMaxLength(100);
            entity.Property(e => e.AccountStaffSize).HasMaxLength(50);
            entity.Property(e => e.AccountStaffSizeSlice).HasMaxLength(50);
            entity.Property(e => e.AccountTaxationSystem).HasMaxLength(100);
            entity.Property(e => e.AccountTaxeValeurAjoutee).HasMaxLength(50);
            entity.Property(e => e.AccountTurnover).HasMaxLength(50);
            entity.Property(e => e.AccountType).HasMaxLength(50);
            entity.Property(e => e.AccountTypeTenueComptable).HasMaxLength(50);
            entity.Property(e => e.BillingAddressLine1).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine2).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine3).HasMaxLength(255);
            entity.Property(e => e.BillingCity).HasMaxLength(50);
            entity.Property(e => e.BillingCountry).HasMaxLength(50);
            entity.Property(e => e.BillingPhone).HasMaxLength(50);
            entity.Property(e => e.BillingState).HasMaxLength(50);
            entity.Property(e => e.BillingZipCode).HasMaxLength(20);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.DeliveryAddressLine1).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine3).HasMaxLength(255);
            entity.Property(e => e.DeliveryCity).HasMaxLength(50);
            entity.Property(e => e.DeliveryCountry).HasMaxLength(50);
            entity.Property(e => e.DeliveryPhone).HasMaxLength(50);
            entity.Property(e => e.DeliveryState).HasMaxLength(50);
            entity.Property(e => e.DeliveryZipCode).HasMaxLength(20);
            entity.Property(e => e.DeploymentStatus).HasMaxLength(50);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.Updated).HasColumnType("datetime");
        });

        modelBuilder.Entity<RegContactEntity>(entity =>
        {
            entity.HasKey(e => e.Email);

            entity.ToTable("Contact", "reg");

            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.JobDescription).HasMaxLength(255);
            entity.Property(e => e.LandPhone).HasMaxLength(255);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MobilePhone).HasMaxLength(255);
            entity.Property(e => e.OfficeCode).HasMaxLength(50);
            entity.Property(e => e.Source).HasMaxLength(20);
        });

        modelBuilder.Entity<RegOperationEntity>(entity =>
        {
            entity.ToTable("Operations", "reg");

            entity.Property(e => e.LastStatusApprovalBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Operation)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ApprovalStatus).HasMaxLength(20);
            entity.Property(e => e.Type)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RegRoleEntity>(entity =>
        {
            entity.HasKey(e => new { e.ContactEmail, e.AccountNumber });

            entity.ToTable("role", "reg");

            entity.Property(e => e.ContactEmail).HasMaxLength(255);
            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.RoleDelegataireEmail).HasMaxLength(200);

            entity.HasOne(d => d.AccountNumberNavigation).WithMany(p => p.RegRoleEntity)
                .HasForeignKey(d => d.AccountNumber)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RegRoleEntity_Account");

            entity.HasOne(d => d.ContactEmailNavigation).WithMany(p => p.RegRoleEntity)
                .HasForeignKey(d => d.ContactEmail)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RegRoleEntity_Contact");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}