// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pulse.Registry.Domain.Entities;
using Pulse.Registry.Domain.Entities.Accounts;
using Pulse.Registry.Domain.Entities.Audits;
using Pulse.Registry.Domain.Entities.Contacts;

namespace Pulse.Registry.Domain.Context;

public partial class RefContext : DbContext
{
    public RefContext(DbContextOptions<RefContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountEntity> AccountEntity { get; set; }

    public virtual DbSet<ContactEntity> ContactEntity { get; set; }

    public virtual DbSet<DeepValidationEntity> DeepValidationEntity { get; set; }

    public virtual DbSet<PendingOperationEntity> PendingOperationEntity { get; set; }

    public virtual DbSet<RefAccountEntity> RefAccountEntity { get; set; }

    public virtual DbSet<RefContactEntity> RefContactEntity { get; set; }

    public virtual DbSet<RefOfferEntity> RefOfferEntity { get; set; }

    public virtual DbSet<RefRoleEntity> RefRoleEntity { get; set; }

    public virtual DbSet<RegOperationEntity> RegOperationEntity { get; set; }

    public virtual DbSet<RoleEntity> RoleEntity { get; set; }

    public virtual DbSet<HubSpotFormEntity> HubSpotFormEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AccountEntity>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("C_Account_PK");

            entity.ToTable("Accounts", "Account");

            entity.HasIndex(e => e.AccountGlobalUniqueId, "UQ_Account_AccountGlobalUniqueId").IsUnique();

            entity.Property(e => e.AccountId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("");
            entity.Property(e => e.ModifiedBy)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ContactEntity>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("C_Contact_PK");

            entity.ToTable("Contacts", "Contact");

            entity.Property(e => e.ContactId).ValueGeneratedNever();
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<DeepValidationEntity>(entity =>
        {
            entity.ToTable("DeepValidations", "Audit");

            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<PendingOperationEntity>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.ToView("PendingOperations", "reg");

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.LegalName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.MobilePhone).HasMaxLength(255);
        });

        modelBuilder.Entity<RefAccountEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Account", "ref");

            entity.Property(e => e.EntityId).ValueGeneratedNever();
            entity.Property(e => e.AccountBillingEmail).HasMaxLength(255);
            entity.Property(e => e.AccountBillingFax).HasMaxLength(50);
            entity.Property(e => e.AccountBillingPhone).HasMaxLength(50);
            entity.Property(e => e.AccountCodeFormeJuridique).HasMaxLength(50);
            entity.Property(e => e.AccountCommercialName).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryEmail).HasMaxLength(255);
            entity.Property(e => e.AccountDeliveryFax).HasMaxLength(50);
            entity.Property(e => e.AccountDeliveryPhone).HasMaxLength(50);
            entity.Property(e => e.AccountEmail).HasMaxLength(100);
            entity.Property(e => e.AccountEscCategory).HasMaxLength(50);
            entity.Property(e => e.AccountFormeJuridique).HasMaxLength(255);
            entity.Property(e => e.AccountIsin)
                .HasMaxLength(100)
                .HasColumnName("AccountISIN");
            entity.Property(e => e.AccountNafIdentifier).HasMaxLength(50);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.AccountRegimeFiscal).HasMaxLength(50);
            entity.Property(e => e.AccountRegisterIdentification1).HasMaxLength(50);
            entity.Property(e => e.AccountSectorCode).HasMaxLength(50);
            entity.Property(e => e.AccountSourceName).HasMaxLength(100);
            entity.Property(e => e.AccountStaffSize).HasMaxLength(50);
            entity.Property(e => e.AccountStaffSizeSlice).HasMaxLength(50);
            entity.Property(e => e.AccountTaxationSystem).HasMaxLength(100);
            entity.Property(e => e.AccountTaxeValeurAjoutee).HasMaxLength(50);
            entity.Property(e => e.AccountTurnover).HasMaxLength(50);
            entity.Property(e => e.AccountType).HasMaxLength(50);
            entity.Property(e => e.AccountTypeTenueComptable).HasMaxLength(50);
            entity.Property(e => e.BillingAddressLine1).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine2).HasMaxLength(255);
            entity.Property(e => e.BillingAddressLine3).HasMaxLength(255);
            entity.Property(e => e.BillingCity).HasMaxLength(50);
            entity.Property(e => e.BillingCountry).HasMaxLength(50);
            entity.Property(e => e.BillingState).HasMaxLength(50);
            entity.Property(e => e.BillingZipCode).HasMaxLength(20);
            entity.Property(e => e.DeliveryAddressLine1).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine3).HasMaxLength(255);
            entity.Property(e => e.DeliveryCity).HasMaxLength(50);
            entity.Property(e => e.DeliveryCountry).HasMaxLength(50);
            entity.Property(e => e.DeliveryState).HasMaxLength(50);
            entity.Property(e => e.DeliveryZipCode).HasMaxLength(20);
            entity.Property(e => e.LegalName).HasMaxLength(255);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<RefContactEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Contact", "ref");

            entity.Property(e => e.EntityId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactSource)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.JobDescription).HasMaxLength(255);
            entity.Property(e => e.LandPhone).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.MobilePhone).HasMaxLength(255);
            entity.Property(e => e.OfficeCode).HasMaxLength(50);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<RefOfferEntity>(entity =>
        {
            entity.ToTable("Offer", "ref");

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.AccountingExpertEmail).HasMaxLength(255);
            entity.Property(e => e.ClientEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.CollaboratorEmail).HasMaxLength(255);
            entity.Property(e => e.MigrationStatus)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MissionLeaderEmail).HasMaxLength(255);
            entity.Property(e => e.Offer)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<RefRoleEntity>(entity =>
        {
            entity.HasKey(e => e.EntityId);

            entity.ToTable("Role", "ref");

            entity.Property(e => e.EntityId).ValueGeneratedNever();
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ContactEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.OperationType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.RoleSource)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SubRole)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ContactFlagPortailFactures)
                .HasColumnType("BIT");
            entity.Property(e => e.ContactFlagMainContact)
                .HasColumnType("BIT");

        });

        modelBuilder.Entity<RegOperationEntity>(entity =>
        {
            entity.ToTable("Operations", "reg");

            entity.Property(e => e.ApprovalStatus).HasMaxLength(20);
            entity.Property(e => e.LastStatusApprovalBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.OldContactEmail).HasMaxLength(255);
            entity.Property(e => e.Operation)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ProcessStatus).HasMaxLength(20);
            entity.Property(e => e.Type)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<RoleEntity>(entity =>
        {
            entity.HasKey(e => new { e.ContactId, e.AccountId }).HasName("C_Role_PK");

            entity.ToTable("Roles", "Account");

            entity.HasIndex(e => new { e.AccountId, e.ContactId }, "C_Role_AccountId_ContactId").IsUnique();

            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.ContactEmail).HasMaxLength(255);
            entity.Property(e => e.ContactFlagPortailFactures)
                  .HasColumnType("BIT");
            entity.Property(e => e.ContactFlagMainContact)
                  .HasColumnType("BIT");

            entity.HasOne(d => d.Account).WithMany(p => p.RoleEntity)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Role_FK");

            entity.HasOne(d => d.Contact).WithMany(p => p.RoleEntity)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("C_Account_Contact_FK");
        });

        modelBuilder.Entity<HubSpotFormEntity>(entity =>
        {
            entity.HasKey(e => new { e.AccountNumber, e.SubmittedBy }).HasName("C_HubspotForm_PK");

            entity.ToTable("HubspotForm", "ext");

            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FormData)
                .IsRequired()
                .HasColumnType("NVARCHAR(MAX)");
            entity.Property(e => e.HubSpotDispatchState)
                .HasColumnType("BIT");
            entity.Property(e => e.SubmittedAt)
                .HasColumnType("DATETIME");
            entity.Property(e => e.SubmittedBy)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
