// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.ContactRegistry.Infrastructure.Entities;

public partial class RefRoleEntity
{
    public int RoleId { get; set; }

    public string ContactEmail { get; set; }

    public string AccountNumber { get; set; }

    public int? RoleFlagStatus { get; set; }

    public string Description { get; set; }

    public string OperationType { get; set; }

    public DateTime OperationDate { get; set; }
}