// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.ContactRegistry.Infrastructure.Entities;

public partial class RegContactEntity
{
    public Guid Id { get; set; }

    public Guid? OfficeId { get; set; }

    public bool IsCustomer { get; set; }

    public bool IsActive { get; set; }

    public DateTime? Updated { get; set; }

    public DateTime? Deleted { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string LandPhone { get; set; }

    public string MobilePhone { get; set; }

    public string JobDescription { get; set; }

    public string Source { get; set; }

    public bool? ContactFlagStatus { get; set; }

    public virtual ICollection<RegRoleEntity> RegRoleEntity { get; set; } = new List<RegRoleEntity>();
}