// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.ContactRegistry.Infrastructure.Entities;

public partial class RegProcessDeltaTriggerEntity
{
    public int Id { get; set; }

    public bool Account { get; set; }

    public bool Role { get; set; }

    public bool Contact { get; set; }
}