// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Pulse.Registry.Domain.Entities.Accounts;
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities.Contacts;

public partial class ContactEntity
{
    public int ContactId { get; set; }

    public Guid? ContactGlobalUniqueId { get; set; }

    public string Email { get; set; }

    public string Type { get; set; }

    public string FirstName { get; set; }

    public string Title { get; set; }

    public string MobilePhone { get; set; }

    public string LastName { get; set; }

    public virtual ICollection<RoleEntity> RoleEntity { get; set; } = new List<RoleEntity>();
}