// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities.Audits;

public partial class DeepValidationEntity
{
    public long Id { get; set; }

    public string Type { get; set; }

    public Guid EntityId { get; set; }

    public string Reason { get; set; }

    public DateTime CreationDate { get; set; } = DateTime.UtcNow;
}