CREATE TABLE [Audit].[DeepValidations]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [Type] NVARCHAR(50) NOT NULL, 
    [EntityId] UNIQUEIDENTIFIER NOT NULL, 
    [Reason] NVARCHAR(500) NOT NULL, 
    [CreationDate] DATETIME2 NOT NULL 
)
