CREATE TABLE [ref].[Account](
    [AccountFlagStatus] [int] NOT NULL,
    [LegalName] [nvarchar](255) NOT NULL,
    [AccountNumber] [nvarchar](50) NOT NULL,
    [AccountCommercialName] [nvarchar](255) NULL,
    [AccountType] [nvarchar](50) NULL,
    [AccountEmail] [nvarchar](100) NULL,
    [AccountNafIdentifier] [nvarchar](50) NULL,
    [AccountSectorCode] [nvarchar](50) NULL,
    [AccountTaxeValeurAjoutee] [nvarchar](50) NULL,
    [AccountDeliveryEmail] [nvarchar](255) NULL,
    [AccountBillingEmail] [nvarchar](255) NULL,
    [AccountTaxationSystem] [nvarchar](100) NULL,
    [AccountSourceName] [nvarchar](100) NULL,
    [AccountISIN] [nvarchar](100) NULL,
    [AccountRegisterIdentification1] [nvarchar](50) NULL,
    [AccountStaffSize] [nvarchar](50) NULL,
    [AccountDeliveryFax] [nvarchar](50) NULL,
    [AccountBillingFax] [nvarchar](50) NULL,
    [AccountTurnover] [nvarchar](50) NULL,
    [AccountRegimeFiscal] [nvarchar](50) NULL,
    [AccountTypeTenueComptable] [nvarchar](50) NULL,
    [AccountFormeJuridique] [nvarchar](255) NULL,
    [AccountStaffSizeSlice] [nvarchar](50) NULL,
    [AccountEscCategory] [nvarchar](50) NULL,
    [AccountCodeFormeJuridique] [nvarchar](50) NULL,
    [AccountInsertedDate] [datetime2] NULL,
    [AccountUpdatedDate] [datetime2] NULL,
    [DeliveryAddressLine1] [nvarchar](255) NULL,
    [DeliveryAddressLine2] [nvarchar](255) NULL,
    [DeliveryAddressLine3] [nvarchar](255) NULL,
    [DeliveryCity] [nvarchar](50) NULL,
    [DeliveryZipCode] [nvarchar](20) NULL,
    [DeliveryCountry] [nvarchar](50) NULL,
    [DeliveryState] [nvarchar](50) NULL,
    [BillingAddressLine1] [nvarchar](255) NULL,
    [BillingAddressLine2] [nvarchar](255) NULL,
    [BillingAddressLine3] [nvarchar](255) NULL,
    [BillingCity] [nvarchar](50) NULL,
    [BillingZipCode] [nvarchar](20) NULL,
    [BillingCountry] [nvarchar](50) NULL,
    [BillingState] [nvarchar](50) NULL,
    [DeploymentStatus] [nvarchar](50) NULL,
    [DeploymentDate] [datetime2] NULL,
    [AccountDeliveryPhone] [nvarchar](50) NULL, 
    [AccountBillingPhone] [nvarchar](50) NULL,
    [Operation] [nvarchar](20) NOT NULL
)
GO
