trigger: none

pool:
  vmImage: 'windows-latest'

parameters:
- name: deployToDev
  displayName: 'Déployer sur DEV'
  type: boolean
  default: false
- name: deployToItg
  displayName: 'Déployer sur ITG'
  type: boolean
  default: true

resources:
  repositories:
  - repository: Pulse
    name: 'Pulse.Operations.Pipelines'
    type: git
    ref: 'refs/heads/Release/v4.0'

extends:
  template: pipelines/quick-build/sql.yaml@Pulse
  parameters:
    deployToDev: ${{ parameters.deployToDev }}
    deployToItg: ${{ parameters.deployToItg }}
    srcPath: src\Registry.Sql.Database\Registry.Sql.Database.sqlproj
    domain: reg
    id: '01'