// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.ContactRegistry.Infrastructure.Entities;

public partial class RegOperationEntity
{
    public int Id { get; set; }

    public string Operation { get; set; }

    public string Type { get; set; }

    public DateTime? PublishedAt { get; set; }

    public Guid EntityId { get; set; }

    public string Status { get; set; }

    public DateTime? LastStatusUpdatedDate { get; set; }

    public string LastStatusUpdatedBy { get; set; }

    public DateTime? CreationDate { get; set; }
}