<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Infrastructure</RootNamespace>
	<UserSecretsId>1f37de2e-40f8-4035-9c54-89761cd9bf84</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Provider\**" />
    <EmbeddedResource Remove="Provider\**" />
    <None Remove="Provider\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.1.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.11.1" />
    <PackageReference Include="EFCore.BulkExtensions" Version="8.0.4" />
    <PackageReference Include="Hangfire" Version="1.8.17" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.17" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
	  <PackageReference Include="Polly" Version="8.4.2" />
	  <PackageReference Include="Pulse.Back.Events" Version="2.74.171" />
	  <PackageReference Include="System.Runtime.Caching" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Registry.Domain\Registry.Domain.csproj" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Registry.Application\Registry.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="EntityConfigurations\" />
	  <Folder Include="RuleValidators\" />
	</ItemGroup>
</Project>
