# Prerequis : installer l'extension VS Code "REST Client" (humao.rest-client)
# Lancer les requetes en cliquant sur "Send Request" au-dessus de chaque bloc
# Les variables sensibles sont dans le fichier .env (format dotenv)

### 1. Variables Globales

@tenant = {{$dotenv TENANT}}
@client_id = {{$dotenv CLIENT_ID}}
@client_secret = {{$dotenv CLIENT_SECRET}}
@scope = {{$dotenv SCOPE}}
@client_id_rate_limiting = {{$dotenv CLIENT_ID_RATE_LIMITING}}
@client_secret_rate_limiting = {{$dotenv CLIENT_SECRET_RATE_LIMITING}}
@baseUrl = {{$dotenv BASE_URL}}

### 2. Récupération du Token Microsoft
# @name login
POST https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}
&scope={{scope}}

### 3. Recherche de compte par nom (Utilise le token du dessus)
@authToken = {{login.response.body.access_token}}

POST {{baseUrl}}/akuiteo/account/search
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "name": {
    "operator": "LIKE",
    "value": "boulangerie du ouassim",
    "wildcards": "*"
  }
}

### 4. Recherche de compte par SIRET
POST {{baseUrl}}/akuiteo/account/search
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "siret": {
    "operator": "IS",
    "value": "72200393604516",
    "wildcards": "*"
  }
}

### 5. Recherche de compte par SIREN
POST {{baseUrl}}/akuiteo/account/search
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "siren": {
    "operator": "IS",
    "value": "722003936",
    "wildcards": "*"
  }
}

### 6. Recherche de compte par code
POST {{baseUrl}}/akuiteo/account/search
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "code": {
    "operator": "IS",
    "value": "9010001710",
    "wildcards": "*"
  }
}

### 7. Recherche de contact par email
POST {{baseUrl}}/akuiteo/contact/search
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "email": {
    "operator": "IS",
    "value": "thhebert@orange.fr"
  }
}

### 8. Création de compte (createAccount)
POST {{baseUrl}}/akuiteo/account
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
"legalName": "Cloud & Data Solutions",
  "siren": "834601478",
  "siret": "83460147800011",
  "legalStructure": "Personne morale",
  "legalFormCode": "EURL",
  "nafCode": "8559A",
  "address": {
    "line1": "21B rue du moulin",
    "zipCode": "75010",
    "city": "Paris",
    "departmentCode": "75",
    "regionCode": "11",
    "countryCode": "FR"
  },
  "caseManagerEmail": "hdbira@rydge.fr",
  "accountManagerEmail": "hdbira@rydge.fr"
}

### 9. Création de contact (createContact)
### isDigitalVaultContact > contact coffre-fort numérique
### isDebtCollectionContact > contact recouvrement
### isMandateSignatory > contact signataire de lettre de mission
POST {{baseUrl}}/akuiteo/contact
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "accountNumber": "9010001710",
  "title": "M",
  "lastName": "Jean",
  "firstName": "Dupont",
  "jobTitle": "Gérant",
  "contactDepartment": "Direction",
  "companyRole": "Président",
  "contactTypes": {
    "isDigitalVaultContact": true, 
    "isDebtCollectionContact": false, 
    "isMandateSignatory": false 
  },
  "email": "hdbira+{{$timestamp}}@conseilescgs.onmicrosoft.com",
  "mobilePhone": "0612345678"
}

### 10. Liste des documents d'un compte (listAccountDocuments)
GET {{baseUrl}}/akuiteo/account/9010001695/documents
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Accept: application/json

### 11. Dépôt d'un document pour un compte (uploadAccountDocument)
### accepte 1 fichier (PDF ou image), multipart/form-data, taille max 5 Mo
POST {{baseUrl}}/akuiteo/account/9010001695/documents
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: multipart/form-data; boundary=----WebAppBoundary

------WebAppBoundary
Content-Disposition: form-data; name="document"; filename="sample.pdf"
Content-Type: application/pdf

< ./files/sample.pdf
------WebAppBoundary--

### 12. Téléchargement d'un document par ID (downloadDocumentById)
GET {{baseUrl}}/documents/500048810/content
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Accept: application/octet-stream

### 13. Téléchargement d'une version spécifique d'un document (downloadDocumentById)
GET {{baseUrl}}/documents/500048810/content?versionNumber=1
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Accept: application/octet-stream

### 14. Recherche des conditions de paiement d'un compte (DoSearchPaymentCondition)
### Retourne les conditions et le mode de paiement du compte
GET {{baseUrl}}/akuiteo/account/9010001695/payment-informations
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Accept: application/json

### 15. Mise à jour des coordonnées bancaires d'un compte (DoUpdateBankingInformation)
### action : ADD | UPDATE | REMOVE
POST {{baseUrl}}/akuiteo/account/9010001695/banking-informations
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

[
  {
    "sepa": {
      "bankDetails": {
        "entity": "30006",
        "counter": "00001",
        "accountNumber": "12345678901",
        "key": "89",
        "domiciliation": "Crédit Agricole"
      },
      "bic": {
        "country": "FR",
        "bank": "AGRI",
        "location": "FR",
        "branch": "PP"
      },
      "iban": {
        "country": "FR",
        "key": "76",
        "accountNumber": "30006000011234567890189"
      }
    },
    "noneSepa": null,
    "statusChangeDate": "2024-05-01T09:00:00.000+0000",
    "statusChangeArgument": {
      "comment": "TEST_CA",
      "status": "VALIDATED"
    },
    "action": "ADD"
  }
]

### 16. Mise à jour générique d'un compte (Update customer by id)
### Payload générique permettant de mettre à jour n'importe quels champs du compte Akuiteo
### Exemple : mise à jour des conditions et du mode de paiement
PATCH {{baseUrl}}/akuiteo/account/9010001710
Authorization: Bearer {{authToken}}
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Content-Type: application/json

{
  "conditionOfPayment": {
    "deadLine": "030",
    "term": "1",
    "day": 29,
    "referenceOnBankStatement": "AMOBILIS"
  },
  "methodOfPayment": "OTHER"
}

### 17. Health check (GetHealthCheck)
GET {{baseUrl}}/health
X-Client-Id: {{client_id_rate_limiting}}
X-Client-Secret: {{client_secret_rate_limiting}}
Accept: application/json

