// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Pulse.Registry.Domain.Entities;

public partial class HubSpotFormEntity
{
    public string SubmittedBy { get; set; }

    public DateTime SubmittedAt { get; set; }

    public string AccountNumber { get; set; }

    public bool HubSpotDispatchState { get; set; }

    public string FormData { get; set; }
}
