// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities;

public partial class PendingOperationEntity
{
    public string AccountNumber { get; set; }

    public string LegalName { get; set; }

    public int Id { get; set; }

    public DateTime? CreationDate { get; set; }

    public string ContactEmail { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int CurrentContactId { get; set; }

    public bool? IsSignatory { get; set; }

    public string MobilePhone { get; set; }
}