// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities;

public partial class RefContactEntity
{
    public Guid EntityId { get; set; } = Guid.NewGuid();

    public int? ContactFlagStatus { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool? IsCustomer { get; set; }

    public string LandPhone { get; set; }

    public string MobilePhone { get; set; }

    public string JobDescription { get; set; }

    public string OperationType { get; set; }

    public DateTime OperationDate { get; set; }

    public string OfficeCode { get; set; }

    public DateTime? ValidationDate { get; set; }

    public string? ContactSource { get; set; } = null;
}