// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities;

public partial class RefOfferEntity
{
    public int Id { get; set; }

    public string AccountNumber { get; set; }

    public string ClientEmail { get; set; }

    public string CollaboratorEmail { get; set; }

    public string MissionLeaderEmail { get; set; }

    public string AccountingExpertEmail { get; set; }

    public string Offer { get; set; }

    public string MigrationStatus { get; set; }

    public Guid BatchId { get; set; }
}