// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities;

public partial class RefRoleEntity
{
    public Guid EntityId { get; set; } = Guid.NewGuid();

    public string ContactEmail { get; set; }

    public string AccountNumber { get; set; }

    public int? RoleFlagStatus { get; set; }

    public string Description { get; set; }

    public string OperationType { get; set; }

    public DateTime OperationDate { get; set; }

    public DateTime? ValidationDate { get; set; }

    public string RoleSource { get; set; }

    public string SubRole { get; set; }
}