// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.Registry.Domain.Entities;

public partial class RegOperationEntity
{
    public int Id { get; set; }

    public string Operation { get; set; }

    public string Type { get; set; }

    public DateTime? PublishedAt { get; set; }

    public required Guid EntityId { get; set; }

    public required string ApprovalStatus { get; set; }

    public string? ProcessStatus { get; set; }

    public DateTime? LastStatusApprovalDate { get; set; }

    public string LastStatusApprovalBy { get; set; }

    public DateTime? LastStatusProcessedDate { get; set; }

    public DateTime? CreationDate { get; set; }

    public bool? CreatedBySystem { get; set; }
}