// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pulse.ContactRegistry.Domain.Entities;

public partial class RegRoleEntity
{
    public string ContactEmail { get; set; }

    public string AccountNumber { get; set; }

    public Guid AccountId { get; set; }

    public Guid ContactId { get; set; }

    public DateTime? Deleted { get; set; }

    public Guid RoleId { get; set; }

    public bool? Onboarded { get; set; }

    public string RoleDelegataireEmail { get; set; }

    public bool? RoleSignatory { get; set; }

    public bool? IsFavorite { get; set; }

    public virtual RegAccountEntity AccountNumberNavigation { get; set; }

    public virtual RegContactEntity ContactEmailNavigation { get; set; }
}