CREATE TABLE [alx].[Account](
    [AccountGlobalUniqueIdentifier] [uniqueidentifier] NOT NULL,
    [AccountFlagEscActif] [bit] NOT NULL,
    [LegalName] [nvarchar](255) NOT NULL,
    [AccountNumber] [nvarchar](50) NULL,
    [AccountISIN] [nvarchar](100) NULL,
    [AccountCommercialName] [nvarchar](255) NULL,
    [AccountNafIdentifier] [nvarchar](50) NULL,
    [AccountSectorCode] [nvarchar](50) NULL,
    [AccountTaxeValeurAjoutee] [nvarchar](50) NULL,
    [AccountDeliveryEmail] [nvarchar](255) NULL,
    [AccountBillingEmail] [nvarchar](255) NULL,
    [AccountTaxationSystem] [nvarchar](100) NULL,
    [AccountSourceName] [nvarchar](100) NULL,
    [AccountRegisterIdentification1] [nvarchar](50) NULL,
    [AccountStaffSize] [nvarchar](50) NULL,
    [AccountDeliveryFax] [nvarchar](50) NULL,
    [AccountBillingFax] [nvarchar](50) NULL,
    [AccountTurnover] [nvarchar](50) NULL,
    [AccountRegimeFiscal] [nvarchar](50) NULL,
    [AccountTypeTenueComptable] [nvarchar](50) NULL,
    [AccountType] [nvarchar](50) NULL,
    [AccountFormeJuridique] [nvarchar](100) NULL,
    [AccountStaffSizeSlice] [nvarchar](50) NULL,
    [AccountEscCategory] [nvarchar](50) NULL,
    [AccountCodeFormeJuridique] [nvarchar](50) NULL,
    [AccountEmail] [nvarchar](100) NULL,
    [AccountInsertedDate] [datetime2] NULL,
    [AccountUpdatedDate] [datetime2] NULL,
    [DeliveryAddressLine1] [nvarchar](255) NULL,
    [DeliveryAddressLine2] [nvarchar](255) NULL,
    [DeliveryAddressLine3] [nvarchar](255) NULL,
    [DeliveryCity] [nvarchar](50) NULL,
    [DeliveryZipCode] [nvarchar](20) NULL,
    [DeliveryCountry] [nvarchar](50) NULL,
    [DeliveryState] [nvarchar](50) NULL,
    [BillingAddressLine1] [nvarchar](255) NULL,
    [BillingAddressLine2] [nvarchar](255) NULL,
    [BillingAddressLine3] [nvarchar](255) NULL,
    [BillingCity] [nvarchar](50) NULL,
    [BillingZipCode] [nvarchar](20) NULL,
    [BillingCountry] [nvarchar](50) NULL,
    [BillingState] [nvarchar](50) NULL,
    [DeploymentStatus] [nvarchar](50) NULL,
    [DeploymentDate] [datetime2] NULL,
    [CreatedBy] [nvarchar](100) NULL,
    [ModifiedBy] [nvarchar](100) NULL
PRIMARY KEY CLUSTERED 
(
    [AccountGlobalUniqueIdentifier] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY], 
    [AccountDeliveryPhone] NVARCHAR(50) NULL, 
    [AccountBillingPhone] NVARCHAR(50) NULL
) ON [PRIMARY]
GO
